import { MilestonePending } from '../components/MilestonePending'
import { PageHeader } from '../components/PageHeader'

export default function Workbench() {
  return (
    <div className="space-y-8">
      <PageHeader
        section="Review"
        title="Workbench"
        description="Keyboard-first adjudication of candidate matches across three confidence bands, with the evidence and any hard-constraint veto shown side by side."
      />
      <MilestonePending
        what="Review tasks are generated by the matching engine."
        milestone="M4"
      />
    </div>
  )
}
